"""
Unified Analytics script for Tree of Thoughts (Game of 24 & Mini Crosswords).

Usage Examples:
    # Scan all Game of 24 results
    python analyze.py results/runs/game24/*.jsonl
    
    # Scan all Mini Crosswords results
    python analyze.py results/runs/crosswords/*.jsonl
    
    # Scan all task results at once!
    python analyze.py results/runs/**/*.jsonl
"""

import json
import re
import sys
from pathlib import Path

# --------------------------------------------------------------------
# Mini Crosswords Evaluation Logic
# --------------------------------------------------------------------
def evaluate_cw_grid(output_grid, ground_truth):
    """
    Compares the generated grid against the ground truth to calculate metrics.
    """
    # Flatten the 5x5 grid into a 1D list of 25 characters
    flat_output = [char.upper() for row in output_grid for char in row]
    truth = [char.upper() for char in ground_truth]

    if len(flat_output) != 25:
        return 0.0, 0.0, 0.0

    # 1. Letter Accuracy: Percentage of correctly placed letters
    correct_letters = sum(1 for o, t in zip(flat_output, truth) if o == t)
    letter_acc = correct_letters / 25.0

    # 2. Word Accuracy: Percentage of correctly completed words (10 total)
    correct_words = 0
    # Check horizontal rows
    for i in range(5):
        if flat_output[i*5:(i+1)*5] == truth[i*5:(i+1)*5]:
            correct_words += 1
    # Check vertical columns
    for i in range(5):
        if flat_output[i::5] == truth[i::5]:
            correct_words += 1
    word_acc = correct_words / 10.0

    # 3. Game Accuracy: 1.0 if the entire grid is flawless, 0.0 otherwise
    game_acc = 1.0 if correct_letters == 25 else 0.0

    return letter_acc, word_acc, game_acc


def reconstruct_grid_from_filled(filled_pairs):
    """Rebuild a 5x5 grid from a list of [clue_id, word] entries in the trace.

    Mirrors BoardState.apply_word so analysis-time scoring can reproduce any
    DFS state without the run-time tracking ever consulting ground truth.
    """
    grid = [['_'] * 5 for _ in range(5)]
    for entry in filled_pairs:
        if not entry or len(entry) < 2:
            continue
        cid, word = entry[0], (entry[1] or "").upper()
        if len(word) != 5 or len(cid) < 2:
            continue
        direction, idx_char = cid[0], cid[1]
        if not idx_char.isdigit():
            continue
        idx = int(idx_char) - 1
        if not (0 <= idx < 5):
            continue
        if direction == 'h':
            for c in range(5):
                grid[idx][c] = word[c]
        elif direction == 'v':
            for r in range(5):
                grid[r][idx] = word[r]
    return grid


def best_state_metrics_from_trace(trace, ground_truth):
    """Paper/repo-style Mini Crosswords ``+ best state`` oracle.

    Only score DFS states that were actually visited and recorded in the trace
    via ``record["filled"]``. Do **not** score every proposed child in
    ``record["moves"]``: children that were pruned were generated, but were not
    reached as DFS states.

    This matches the original repo's idea of selecting the best recorded DFS
    state after the run using ground truth. The repo selects by word accuracy
    (``r_word``), so this function uses word accuracy as the primary oracle key,
    with letter accuracy and game accuracy only as tie-breakers.

    Returns (letter_acc, word_acc, game_acc).
    """
    best = (0.0, 0.0, 0.0)

    def _oracle_key(metrics):
        l_acc, w_acc, g_acc = metrics
        return (w_acc, l_acc, g_acc)

    for record in trace or []:
        filled_pairs = record.get("filled", []) or []
        grid = reconstruct_grid_from_filled(filled_pairs)
        metrics = evaluate_cw_grid(grid, ground_truth)

        if _oracle_key(metrics) > _oracle_key(best):
            best = metrics

    return best

def summarize_cw(rows, path, best_state: bool = False):
    """Aggregates statistics for a Mini Crosswords JSONL file.

    When ``best_state`` is True, scores each puzzle using the best actually
    visited DFS state recorded in its trace (paper/repo-style "+ best state"
    oracle). The DFS itself never sees ground truth; this is purely an
    analysis-time computation.
    """
    n = len(rows)
    total_letter, total_word, total_game, total_steps = 0.0, 0.0, 0.0, 0.0

    for row in rows:
        # Prefer pre-calculated averages (generated by IO/CoT multi-sampling)
        if "avg_letter_acc" in row:
            l_acc = row["avg_letter_acc"]
            w_acc = row["avg_word_acc"]
            g_acc = row["avg_game_acc"]
        elif best_state:
            l_acc, w_acc, g_acc = best_state_metrics_from_trace(
                row.get("trace", []), row.get("ground_truth", [])
            )
        else:
            # Final-state evaluation (used by ToT)
            grid = row.get("grid", row.get("inputs", []))
            truth = row.get("ground_truth", [])
            l_acc, w_acc, g_acc = evaluate_cw_grid(grid, truth)

        total_letter += l_acc
        total_word += w_acc
        total_game += g_acc
        total_steps += row.get("steps", 0)

    return {
        "task": "crosswords",
        "file": Path(path).name,
        "n": n,
        "letter_acc": (total_letter / n) * 100,
        "word_acc": (total_word / n) * 100,
        "game_acc": (total_game / n) * 100,
        "avg_steps": total_steps / n,
        "best_state": best_state,
    }

# --------------------------------------------------------------------
# Game of 24 Evaluation Logic
# --------------------------------------------------------------------
def summarize_24(rows, path):
    """Aggregates statistics for a Game of 24 JSONL file."""
    n = len(rows)
    # Count the number of successfully verified puzzles
    successes = sum(1 for r in rows if r.get("verified", False))
    total_steps = sum(r.get("steps", 1) for r in rows)

    return {
        "task": "24",
        "file": Path(path).name,
        "n": n,
        "success_rate": (successes / n) * 100,
        "avg_steps": total_steps / n
    }

# --------------------------------------------------------------------
# Routing and Display Logic
# --------------------------------------------------------------------
def summarize_file(path: str):
    """Reads a JSONL file and routes it to the appropriate evaluator.

    Returns a list of summary dicts. Crosswords ToT runs return both a
    final-state and a trace-derived "+best state" summary; everything else
    returns a single summary.
    """
    try:
        with open(path, "r") as f:
            rows = [json.loads(line) for line in f]
    except Exception:
        return []

    if not rows:
        return []

    # Automatically identify the task type based on the JSON payload footprint
    if "grid" in rows[0] or "avg_letter_acc" in rows[0] or "cw_" in Path(path).name:
        summaries = [summarize_cw(rows, path)]
        # Only ToT runs produce a trace we can replay for "+best state"
        if any(r.get("trace") for r in rows):
            summaries.append(summarize_cw(rows, path, best_state=True))
        return summaries
    else:
        return [summarize_24(rows, path)]

def display_name(filename: str, best_state: bool = False) -> str:
    """Sanitizes the raw filename into a readable format for the table."""
    name = filename.replace(".jsonl", "").replace("cw_gem31_", "").replace("gem31_", "").replace("_papersplit", "")

    # Baselines
    if name == "io": return "IO"
    if name == "cot": return "CoT"

    parts = name.split("_")
    if parts[0] != "tot":
        return name

    display = ["ToT"]

    # Game of 24 specific parameters
    if "b1" in name: display.append("b=1")
    if "b5" in name: display.append("b=5")

    # Batched evaluation ablations. New filenames: tot_<level>_<flags>_s<N>...
    # where <level> is full|half and <flags> is any subset of
    # {basic, focused, verified, cache} joined by '_', optionally with a
    # 'k<N>' segment (top_k value when --focused). Plus 'tot_unbatched_'
    # for the paper-strict per-clue evaluator. Match generically by lifting
    # the segment between 'tot_' and the '_s<digits>' step marker.
    eval_match = re.search(r"tot_(?P<eval>[a-z0-9_]+?)_s\d+", name)
    matched = False
    if eval_match:
        eval_token = eval_match.group("eval")
        valid_levels = {"unbatched", "full", "half"}
        valid_flags = {"basic", "focused", "verified", "cache"}
        parts = eval_token.split("_")
        if parts and parts[0] in valid_levels and all(
            (p in valid_flags) or re.fullmatch(r"k\d+", p)
            for p in parts[1:]
        ):
            display.append(eval_token.replace("_", " "))
            matched = True

    if not matched:
        # Legacy filename patterns (kept so old result JSONLs still display).
        if "robust_batched" in name: display.append("robust batched")
        elif "basic_batched" in name: display.append("basic batched")
        elif "unbatched" in name: display.append("unbatched")
        elif "batched" in name: display.append("batched")

    # Search ablations
    if "noprune" in name: display.append("- prune")
    if "nobacktrack" in name: display.append("- backtrack")

    # Trace-derived oracle metric (computed at analysis time)
    if best_state: display.append("+ best state")

    final_name = " / ".join(display)

    # Post-processing flags
    if "rescored" in filename: final_name += " (+ rescore)"

    return final_name

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    results_24 = []
    results_cw = []

    # Parse and categorize all provided files
    for path in sys.argv[1:]:
        for stats in summarize_file(path):
            if stats["task"] == "24":
                results_24.append(stats)
            else:
                results_cw.append(stats)

    # --------------------------------------------------
    # Render Game of 24 Table
    # --------------------------------------------------
    if results_24:
        print("\n=== Game of 24 Results ===")
        table_24 = [(display_name(s["file"]), s) for s in results_24]

        # Sort layout: IO -> CoT -> ToT variations
        table_24.sort(key=lambda x: (x[0] != "IO", x[0] != "CoT", x[0]))

        header_title = "Method / File"
        name_width = max(len(header_title), max(len(m) for m, _ in table_24)) + 2
        header = f"{header_title:<{name_width}} {'n':>4} {'Success%':>9} {'Steps':>7}"

        print("=" * len(header))
        print(header)
        print("-" * len(header))
        for m, s in table_24:
            print(f"{m:<{name_width}} {s['n']:>4} {s['success_rate']:>8.1f}% {s['avg_steps']:>7.1f}")
        print("=" * len(header))

    # --------------------------------------------------
    # Render Mini Crosswords Table
    # --------------------------------------------------
    if results_cw:
        print("\n=== Mini Crosswords Results ===")
        table_cw = [(display_name(s["file"], s.get("best_state", False)), s) for s in results_cw]

        # Sort layout: IO -> CoT -> ToT variations
        table_cw.sort(key=lambda x: (x[0] != "IO", x[0] != "CoT", x[0]))
        
        header_title = "Method / File"
        name_width = max(len(header_title), max(len(m) for m, _ in table_cw)) + 2
        header = f"{header_title:<{name_width}} {'n':>4} {'Letter%':>8} {'Word%':>8} {'Game%':>8} {'Steps':>7}"
        
        print("=" * len(header))
        print(header)
        print("-" * len(header))
        for m, s in table_cw:
            print(f"{m:<{name_width}} {s['n']:>4} {s['letter_acc']:>7.1f}% {s['word_acc']:>7.1f}% {s['game_acc']:>7.1f}% {s['avg_steps']:>7.1f}")
        print("=" * len(header) + "\n")

if __name__ == "__main__":
    main()